@startuml
autonumber
'hide footbox

actor "Utilizador autenticado/ não autenticado" as u

activate u
u->":UI": Consultar Leader board - Dimensão de rede
activate ":UI"
":UI"->":UI": Sucesso na execução da funcionalidade
":UI"-->u: Mostra a leader board
deactivate ":UI"
deactivate u
@enduml
