@startuml
autonumber
'hide footbox

participant "SPA UI" as ui
participant "MDR" as mdr
participant "ARS" as ars
participant "MDP" as mdp

activate ui
activate mdr
ui->mdr: .get(/api/utilizadores)
mdr->mdr: encontra utilizadores \n com tags iguais  \n e adiciona ao "response body"
mdr-->ui: status da resposta
deactivate ui
deactivate mdr
@enduml
