@startuml
autonumber
'hide footbox

participant "UI" as ui
participant "MDR" as mdr
participant "ARS" as ars


activate ui
activate mdr
ui->mdr: .get(/api/requests)
mdr->mdr: encontra todos os pedidos\n de ligação pendentes e\n retorna estes pedidos
mdr-->ui: status da resposta
deactivate ui
deactivate mdr
@enduml
