@startuml
autonumber
'hide footbox

		participant "UI" as ui
		participant "MDR" as mdr
    participant "Relation" as rel
    participant "Controller" as ctrl
    participant "Repository" as repo

    activate ui
		ui->mdr:get(/api/relations/idUser1)
    activate mdr

    mdr->rel: get
    activate rel
    rel->ctrl:getRelationFriends(id)
    activate ctrl
    ctrl->ctrl: recebe o request body
		ctrl->repo: findAll
    activate repo
    repo->repo: consulta a DB
    repo-->ctrl: anexa a(s) relação(s) ao response body
    deactivate repo
    ctrl-->rel: return
    deactivate ctrl
    rel-->mdr: status 200
    deactivate rel
    mdr-->ui: mostra a força das relações resultante
    deactivate mdr
    deactivate ui
@enduml
