@startuml
autonumber
'hide footbox

participant "SPA UI" as ui
participant "MDR" as mdr
participant "ARS" as ars
participant "MDP" as mdp

activate ui
activate mdr
ui->mdr: .get(/api/tags)
mdr->mdr: encontra todas \nas tags utilizadas nas relações do utilizador \n e adciona ao "response body"
mdr-->ui: status da resposta
deactivate ui
deactivate mdr
@enduml
