@startuml
autonumber
'hide footbox

participant "User" as usr
participant "UI" as ui
participant "HTML" as html
participant "Component" as cmp
participant "Service" as srv
participant "MDR" as mdr
participant "ARS" as ars


activate usr
usr->ui: getAll
activate ui
ui->html: getAll
activate html
html->cmp: chamada da component estado-humor
activate cmp
cmp->srv: getAll
activate srv
srv->mdr: getAll
activate mdr
mdr->ars: envia relacoes
activate ars
ars->ars: processa relacoes
ars-->mdr: envia relaçoes necessárias à construção da rede
deactivate ars
mdr-->srv: return list de relacoes e status 200
deactivate mdr
srv-->cmp: devolve lista
deactivate srv
cmp -->html: devolve lista
cmp --> cmp: processa lista para criação de rede visual
html-->ui:recebe rede
deactivate cmp
deactivate html
ui-->usr: recebe rede e apresenta ao user
deactivate ui
deactivate usr






@enduml
