@startuml
autonumber
'hide footbox

participant "UI" as ui
participant "MDR" as mdr
participant "ARS" as ars


activate ui
activate mdr
ui->mdr: .get(/api/estado_humor)
mdr->mdr: lida com o request body,\n mostra os estados de humor existentes
mdr-->ui: status da resposta
ui->mdr: .put(/api/estado_humor)
mdr->mdr: lida com o request body,\n atualiza o estado de humor
mdr-->ui: status da resposta
deactivate ui
deactivate mdr
@enduml